name: CI/CD for Web (www)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check for package.json
        id: check_files
        run: |
          if [ -f "package.json" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        if: env.exists == 'true'
        run: npm install

      - name: Run Tests
        if: env.exists == 'true'
        run: npm test -- --passWithNoTests

      - name: Build Project
        if: env.exists == 'true'
        run: npm run build

      - name: Deploy (Placeholder)
        if: github.ref == 'refs/heads/main'
        run: echo "Deployment step will be added later."